FROM centos:7

# Add the old repos as centos7 is deprecated
RUN sed -i \
    -e 's|^mirrorlist=|#mirrorlist=|g' \
    -e 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' \
    /etc/yum.repos.d/CentOS-Base.repo

# Install all the requirements for diamond, questasim and other goodies
RUN yum -y update && yum -y install \
    cmake \
    git \
    vim \
    && yum -y groupinstall "Development Tools" \
    && yum clean all

# Clone MARTe2
RUN git clone https://github.com/aneto0/MARTe2.git /opt/MARTe2

# Clone MARTe2 Components
RUN git clone https://vcis-gitlab.f4e.europa.eu/aneto/MARTe2-components.git /opt/MARTe2-components

# Build Marte2
WORKDIR /opt/MARTe2
RUN make -f Makefile.linux

# Environment
ENV MARTe2_DIR=/opt/MARTe2
ENV MARTe2_Components_DIR=/opt/MARTe2-components
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MARTe2_DIR/Build/x86-linux/Core/

WORKDIR /workspace
